### ISSUE TITLE
Not finding the Java Version during install

### ISSUE THREAD

**Issue by OliverMoscow** [HIEofOne/Trustee-Community#16]
After performing `$sudo ./do-install.sh` I get the following error message: `NVM not installed.  Installing all dependencies for Trustee-Community...
The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
Please visit http://www.java.com for information on installing Java.`

Further info: 

- My Java version is installed... When I run `$which java` it returns`/usr/bin/java`

- I am using a mac m1 pro running Monterey

- I ran `$git clone -b deploy --single-branch https://github.com/HIEofOne/Trustee-Community.git
$cd Trustee-Community` commands first
- I also have node installed. When I run `node --version` i get `v19.4.0`

**Comment by shihjay2** [comment]
The do-install bash script is only valid for linux-based systems (or even more specifically, DigitalOcean droplets with Ubuntu) - apt is the default package manager for Ubuntu.
