### ISSUE TITLE
Couch db setup not working

### ISSUE THREAD

**Issue by OliverMoscow** [HIEofOne/Trustee-Community#17]
I have followed the installation instructions on the readme. For some reason the last two checks are not working. What could I do to fix this?

<img width="1032" alt="Screen Shot 2023-09-16 at 3 08 09 PM" src="https://github.com/HIEofOne/Trustee-Community/assets/56978722/05e9e2b4-b10a-453a-8c40-ee10590681e4">

**Comment by shihjay2** [comment]
This is because shihjay2/trusteecommunity does not exist on Docker Hub (it’s manually built on my development machine and then uploaded via SSH to the droplet).  I will plan to add this to GitHub Actions in the next couple of weeks.

Michael
